### ISSUE TITLE
How can I get the refined pose of custom data?

### ISSUE THREAD

**Issue by InckieUltra** [JiahuiLei/GART#12]
I notice that there is a refined pose in peoplesnapshot. I wonder if I can get such refined pose on custom data.
Many thanks :) !

**Comment by JiahuiLei** [comment]
Thanks for your question. The refined poses used for people snapshot are from instant-avatar https://tijiang13.github.io/InstantAvatar/ which affects the quantitative numbers for fair comparison but does not affect too much the visual results.  So I guess it may not be that important to get the refined poses for in the wild data.
