### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by pansanity666** [JiahuiLei/GART#4]
Hi, 
I have got this error when runing 'bash script/fit_people_30s.sh'
![image](https://github.com/JiahuiLei/GART/assets/47111102/c0e3b81b-1d19-4332-8c1d-92c553d3e63b)

Do you have any idea about it? 

Best,

**Comment by JiahuiLei** [comment]
Thanks for your interest, most likely the Gaussian rasterizer is in the wrong version so the dep and alpha are empty, do you install the alpha-dep version (included in our repo already) of diff-gaussian-rasterization?

**Comment by pansanity666** [comment]
Hi, 
    I installed  the rasterizer from the gaussian splatting official repo. I think you are right. By the way, the mask loss is not used, right?
Best,

**Comment by JiahuiLei** [comment]
Thanks for your interest, we do NOT use the mask loss, for some unknown reason, enabling it will make the results worse and more noisy.

**Comment by pansanity666** [comment]
Thx, I got it.

**Comment by pansanity666** [comment]
Hi,

I still have several questions.
Is the only difference between alpha-dep and the original versions is the additional alpha and depth outputs? 
Did you modify it yourself or from the official rep? 

Best,
