### ISSUE TITLE
About dL_depth and dL_mean

### ISSUE THREAD

**Issue by zhao-yiqun** [JiahuiLei/GART#6]
Hi Jiahui

Thanks for your code releasing! 

I am trying to develop the depth supervision based on your lib_render and  noticed that you have modify the differentiable_renderer in lib_render 

[dL_dmean](https://github.com/JiahuiLei/GART/blob/main/lib_render/diff_gaussian_rasterization-alphadep/cuda_rasterizer/backward.cu#L379)

It seems that the gradients of mean3D did not include depth and alpha for back progration.I would like to know if this is intentional on your part?(I mean will this make the results more better? etc..) Based on my understanding, the gradient from dL_ddepths and dL_dalphas should also be include to the gradient of means3D.

**Comment by JiahuiLei** [comment]
Thanks for your interest! This part of the code is borrowed early from DreamGaussian https://github.com/dreamgaussian/dreamgaussian , i.e. this implementation https://github.com/ashawkey/diff-gaussian-rasterization . I noticed that they recently supported depth backward, maybe you would find theirs useful.

**Comment by zhao-yiqun** [comment]
Thanks !
